# Generated by Django 6.0.4 on 2026-04-29 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='dashboard.loja'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel',
            field=models.CharField(choices=[('ADMIN', 'Nexus Hub'), ('DONO', 'Dono da Loja'), ('GERENTE', 'Gerente'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10),
        ),
    ]
