# Generated by Django 6.0.4 on 2026-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_funcionario_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to='produtos/galeria/'),
        ),
    ]
