# Generated by Django 6.0.4 on 2026-06-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_produtoimagem_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoimagem',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='produtoimagem',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='produtoimagem',
            table='dashboard_produtoimagem',
        ),
    ]
