# Generated by Django 6.0.4 on 2026-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_produtoimagem_options_produtoimagem_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_oferta',
            field=models.BooleanField(default=False, verbose_name='Ativar Promoção?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço com Desconto'),
        ),
    ]
